name: eitta mirror

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  start-sending:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
    - name: Send to TG
      run: |
        pip install requests
        python3 main.py
      env:
        TOKEN: ${{ secrets.TOKEN }}
        CHANNEL: ${{ secrets.CHANNEL }}

    - name: commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "update post number" -a || :

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
